name = "durable-objects-test-v2"
#main = "src/index.ts"
compatibility_date = "2025-07-07"
#compatibility_flags = ["nodejs_compat"]
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "test_db"
database_id = "895db7b3-ef54-4fdc-a2ff-d8a05b8973d0"

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[build]
upload_source_maps = true

[build.upload]
format = "service-worker" # 或者 modules，看你的构建方式
dir = "./dist"
main = "src/index.ts"

[build.source_maps]
base_dir = "./dist"
files = ["**/*.map"]